//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleExposicion
    {
        public int Id { get; set; }
        public int IdExposicion { get; set; }
        public Nullable<int> IdObra { get; set; }
    
        public virtual Exposicion Exposicion { get; set; }
        public virtual Obra Obra { get; set; }
    }
}
