//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obra
    {
        public Obra()
        {
            this.DetalleExposicion = new HashSet<DetalleExposicion>();
        }
    
        public int Id { get; set; }
        public Nullable<decimal> Alto { get; set; }
        public Nullable<decimal> Ancho { get; set; }
        public string CodigoSensor { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> DuracionExtendida { get; set; }
        public Nullable<int> DuracionResumida { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaPrimeroIngreso { get; set; }
        public string NombreObra { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public Nullable<decimal> Valuacion { get; set; }
    
        public virtual ICollection<DetalleExposicion> DetalleExposicion { get; set; }
    }
}
