//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sede
    {
        public Sede()
        {
            this.Entrada = new HashSet<Entrada>();
            this.Exposicion = new HashSet<Exposicion>();
            this.ReservaVisita = new HashSet<ReservaVisita>();
            this.Tarifa = new HashSet<Tarifa>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> CantMaxPorGuia { get; set; }
        public Nullable<int> CantMaximaVisitantes { get; set; }
    
        public virtual ICollection<Entrada> Entrada { get; set; }
        public virtual ICollection<Exposicion> Exposicion { get; set; }
        public virtual ICollection<ReservaVisita> ReservaVisita { get; set; }
        public virtual ICollection<Tarifa> Tarifa { get; set; }
    }
}
