//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarifa
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaInicioVigencia { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<decimal> MontoAdicionalGuia { get; set; }
        public Nullable<int> IdSede { get; set; }
        public Nullable<int> IdTipoEntrada { get; set; }
        public Nullable<int> IdTipoVisita { get; set; }
    
        public virtual Sede Sede { get; set; }
        public virtual TipoEntrada TipoEntrada { get; set; }
        public virtual TipoVisita TipoVisita { get; set; }
    }
}
